[package]
name = "exsilium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.6.1", features = ["dynamic"] }
rand = "0.8.2"
leafwing-input-manager = "0.2"